from odoo import fields, models, api
from odoo.exceptions import ValidationError


class FuelCreditPayment(models.Model):
    _name = "fuel.credit.payment"
    _description = "Credit Payment Receipt"
    _order = "date desc, id desc"

    name = fields.Char(default="New", readonly=True)
    date = fields.Datetime(required=True, default=fields.Datetime.now, index=True)

    shift_id = fields.Many2one("fuel.shift", required=True)
    attendant_id = fields.Many2one("fuel.attendant", required=True)

    # Set by action_populate_shift_transactions — not at creation.
    session_id = fields.Many2one(
        "fuel.attendant.session",
        index=True,
        ondelete="set null",
        copy=False,
    )

    receipt_no = fields.Char()
    invoice_ref = fields.Char(
        related="invoice_id.name",
        string="Invoice Reference",
        store=True,
        readonly=True,
    )
    customer_id = fields.Many2one("res.partner", required=True)
    total_balance = fields.Float(string="Outstanding Balance", readonly=True)
    amount_paid = fields.Float(required=True)

    payment_method = fields.Selection(
        [("cash", "Cash"), ("cheque", "Cheque")], required=True
    )

    # Cheque-specific fields — only meaningful when payment_method == 'cheque'
    cheque_no = fields.Char(string="Cheque No")
    cheque_date = fields.Date(string="Cheque Date")
    drawee_bank = fields.Char(string="Drawee Bank")
    clearance_status = fields.Selection(
        [("pending", "Pending"), ("cleared", "Cleared"), ("bounced", "Bounced")],
        string="Clearance Status",
        default="pending",
        index=True,
    )
    clearance_date = fields.Date(string="Clearance Date", readonly=True)
    bounce_reason = fields.Text(string="Bounce Reason")

    station_close_id = fields.Many2one("fuel.station.shift.close", index=True)

    # The specific invoice being settled. Domain is filtered by customer_id in the view.
    invoice_id = fields.Many2one(
        "account.move",
        string="Invoice",
        index=True,
        ondelete="set null",
        copy=False,
        domain="[('move_type', '=', 'out_invoice'), ('state', '=', 'posted'), "
               "('payment_state', 'in', ['not_paid', 'partial']), "
               "('partner_id', '=', customer_id)]",
        help="Select the specific invoice being settled. "
             "Leave empty to record a general payment for this customer.",
    )

    # Kept for backward compatibility: links to the fuel module's credit sale record
    # when the invoice was generated by a credit sale. Auto-populated from invoice_id.
    credit_sale_id = fields.Many2one(
        "fuel.credit.sale",
        string="Credit Sale",
        index=True,
        ondelete="set null",
        copy=False,
    )

    # Accounting payment created automatically on save when an invoice is linked.
    payment_id = fields.Many2one(
        "account.payment",
        string="Accounting Payment",
        readonly=True,
        copy=False,
        ondelete="set null",
    )

    currency_id = fields.Many2one(
        'res.currency',
        compute='_compute_currency_id',
        string='Currency',
    )

    # ------------------------------------------------------------------
    # ORM overrides
    # ------------------------------------------------------------------

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if vals.get("name", "New") == "New":
                vals["name"] = (
                    self.env["ir.sequence"].next_by_code("fuel.credit.payment")
                    or "CP/"
                )
        records = super().create(vals_list)
        for rec in records:
            rec._apply_accounting_payment()
        return records

    @api.depends_context('company')
    def _compute_currency_id(self):
        for rec in self:
            rec.currency_id = self.env.company.currency_id

    # ------------------------------------------------------------------
    # Onchange
    # ------------------------------------------------------------------

    @api.onchange("invoice_id")
    def _onchange_invoice_id(self):
        if self.invoice_id:
            self.customer_id = self.invoice_id.partner_id
            self.total_balance = self.invoice_id.amount_residual
            # Silently link credit_sale_id if this invoice was generated by a credit sale
            cs = self.env["fuel.credit.sale"].search(
                [("move_id", "=", self.invoice_id.id)], limit=1
            )
            self.credit_sale_id = cs or False
        else:
            self.customer_id = False
            self.total_balance = 0.0
            self.credit_sale_id = False

    @api.onchange("customer_id")
    def _onchange_customer_id(self):
        # If the current invoice belongs to a different customer, clear it
        if self.invoice_id and self.invoice_id.partner_id != self.customer_id:
            self.invoice_id = False
            self.credit_sale_id = False

        if self.customer_id and not self.invoice_id:
            # Show total outstanding across all posted invoices for this customer
            invoices = self.env["account.move"].search([
                ("partner_id", "=", self.customer_id.id),
                ("move_type", "=", "out_invoice"),
                ("state", "=", "posted"),
                ("payment_state", "in", ["not_paid", "partial"]),
            ])
            self.total_balance = sum(invoices.mapped("amount_residual"))
        elif not self.customer_id and not self.invoice_id:
            self.total_balance = 0.0

    # ------------------------------------------------------------------
    # Constraints
    # ------------------------------------------------------------------

    @api.constrains("amount_paid")
    def _check_amount_paid(self):
        for rec in self:
            if rec.amount_paid <= 0:
                raise ValidationError("Amount paid must be greater than 0.")

    @api.constrains("amount_paid", "invoice_id")
    def _check_amount_not_over_outstanding(self):
        for rec in self:
            if not rec.invoice_id:
                continue
            if rec.amount_paid > rec.invoice_id.amount_residual + 0.01:
                raise ValidationError(
                    f"Amount paid ({rec.amount_paid:.2f}) exceeds the outstanding balance "
                    f"({rec.invoice_id.amount_residual:.2f}) on invoice {rec.invoice_id.name}."
                )

    # ------------------------------------------------------------------
    # Accounting
    # ------------------------------------------------------------------

    def _apply_accounting_payment(self):
        """
        Create and post an account.payment reconciled against the selected invoice
        when both conditions are met:
          1. An invoice_id is set and is posted.
          2. The matching journal is configured in fuel.station.config.

        If the journal is not configured the record saves normally.
        """
        self.ensure_one()
        if not self.invoice_id or self.invoice_id.state != "posted":
            return

        config = self.env["fuel.station.config"].get_config()
        journal = config.cash_journal_id if self.payment_method == "cash" else config.cheque_journal_id
        if not journal:
            return

        payment = self.env["account.payment"].create({
            "payment_type": "inbound",
            "partner_type": "customer",
            "partner_id": self.customer_id.id or self.invoice_id.partner_id.id,
            "amount": self.amount_paid,
            "journal_id": journal.id,
            "date": self.date.date() if self.date else fields.Date.today(),
            "memo": f"Credit payment: {self.name} — {self.invoice_id.name}",
        })
        payment.action_post()

        inv_line = self.invoice_id.line_ids.filtered(
            lambda l: l.account_id.account_type == "asset_receivable" and not l.reconciled
        )
        pay_line = payment.move_id.line_ids.filtered(
            lambda l: l.account_id.account_type == "asset_receivable" and not l.reconciled
        )
        if inv_line and pay_line:
            (inv_line + pay_line).reconcile()

        self.payment_id = payment.id

    # ------------------------------------------------------------------
    # Smart button actions
    # ------------------------------------------------------------------

    def action_view_invoice(self):
        self.ensure_one()
        return {
            "type": "ir.actions.act_window",
            "res_model": "account.move",
            "view_mode": "form",
            "res_id": self.invoice_id.id,
        }

    def action_view_accounting_payment(self):
        self.ensure_one()
        return {
            "type": "ir.actions.act_window",
            "res_model": "account.payment",
            "view_mode": "form",
            "res_id": self.payment_id.id,
        }

    # ------------------------------------------------------------------
    # Cheque clearance actions
    # ------------------------------------------------------------------

    def action_mark_cleared(self):
        self.ensure_one()
        if self.payment_method != "cheque":
            raise ValidationError("Only cheque payments can be marked as cleared.")
        if self.clearance_status != "pending":
            raise ValidationError("This cheque is already %s." % self.clearance_status)
        self.write({
            "clearance_status": "cleared",
            "clearance_date": fields.Date.today(),
        })

    def action_mark_bounced(self):
        self.ensure_one()
        if self.payment_method != "cheque":
            raise ValidationError("Only cheque payments can be marked as bounced.")
        if self.clearance_status != "pending":
            raise ValidationError("This cheque is already %s." % self.clearance_status)

        # Reverse the accounting payment so the invoice goes back to unpaid.
        if self.payment_id and self.payment_id.state == "posted":
            # Unreconcile any receivable lines before resetting to draft.
            reconciled_lines = self.payment_id.move_id.line_ids.filtered(
                lambda l: l.account_id.account_type == "asset_receivable" and l.reconciled
            )
            if reconciled_lines:
                reconciled_lines.remove_move_reconcile()
            self.payment_id.action_draft()
            self.payment_id.action_cancel()

        self.write({
            "clearance_status": "bounced",
            "clearance_date": fields.Date.today(),
        })
